micronaut:
  application:
    name: shopMultiAgent
  router:
    static-resources:
      default:
        paths: classpath:public
        mapping: /**

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION_KEY_PROPERTY}

langchain4j:
  bedrock:
    chat-model:
      model-id: ${AWS_BEDROCK_MODEL_ID}
      region: ${AWS_REGION_KEY_PROPERTY}
      timeout: 60s
      max-output-tokens: 4096
      temperature: 0.2
